// <auto-generated />
using System;
using MatriculasService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatriculasService.Infrastructure.Migrations
{
    [DbContext(typeof(MatriculaDbContext))]
    [Migration("20260329120715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatriculasService.Infrastructure.Persistence.Entities.MatriculaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uuid")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("PeriodoAno")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_ano");

                    b.Property<int>("PeriodoSemestre")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_semestre");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_matriculas");

                    b.HasIndex("AlunoId", "DisciplinaId", "PeriodoAno", "PeriodoSemestre")
                        .HasDatabaseName("ix_matriculas_aluno_disciplina_periodo")
                        .HasFilter("status = 'Confirmada'");

                    b.ToTable("matriculas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
